FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates

RUN pip install --upgrade -r requirements.txt

ENTRYPOINT [ "/bin/bash" ]